version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: dockerrootpwd
      MYSQL_DATABASE: counterdb
      MYSQL_USER: dockeruser
      MYSQL_PASSWORD: dockerpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - workshop-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: workshop-app-mysql:compose
    container_name: express-container
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - workshop-network

volumes:
  db_data:

networks:
  workshop-network:
    driver: bridge
